### ISSUE TITLE
Music doesn't play after watching video in menu

### ISSUE THREAD

**Issue by muczc1wek** [Silver-Ore-Team/zBassMusic#1]
The music does not start playing back after watching the video in the menu (authors list or intro).
I checked this case in CoM and there the music plays back after the video ends.
(Version v0.0.12)

**Comment by Shoun2137** [comment]
TCoM shouldn't be tested with such plugins, because they're using their own custom music backend. If that doesn't work for vanilla game, the it's a bug.

**Comment by muczc1wek** [comment]
@Shoun2137 I meant I chcecked what will happen with music in CoM when I will play a Video in menu, not that I used this plugin in CoM.
