### ISSUE TITLE
Invalid hook definition

### ISSUE THREAD

**Issue by UnresolvedExternal** [Silver-Ore-Team/zBassMusic#5]
You must deactivate hooks that are not intended for the version of the game the plugin was running on.
Use something like `GetGameVersion() == ENGINE ? zSwitch(0x004240C0, 0x00424C70) : 0`
https://github.com/Silver-Ore-Team/zBassMusic/blob/3bd3c4c7dd756bf1cc25fc7b6eff3ac07a3bdb3f/plugin/src/Gothic/Hooks.hpp#L5-L11

**Comment by piotrmacha** [comment]
Fixed in v0.0.21
